version: '3'

services:
  backend:
    env_file:
        "./backend/backend.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "mern-separated-backend"
    ports:
      - "5001:5001"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "mern-separated-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"